# Travis CI instructions

sudo: required
dist: trusty
language: generic

cache: ccache

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
      - c.henkel@pilz.de
      - h.slusarek@pilz.de
      - i.martini@pilz.de

env:
  global:
    - ROS_DISTRO=melodic
    - DOCKER_IMAGE=moveit/moveit:master-ci

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
